# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.cache/wt} [current_project]
set_property parent.project_path {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/siddh/Desktop/Lab5 - Final Project/lab5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5Files/timing.v}}
read_vhdl -library xil_defaultlib {
  {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5Files/ClockGen.vhd}
  {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5Files/DVI_Constants.vhd}
  {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5Files/SyncAsync.vhd}
  {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5Files/SyncAsyncReset.vhd}
  {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5Files/OutputSERDES.vhd}
  {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5Files/TMDS_Encoder.vhd}
  {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5Files/rgb2dvi.vhd}
  {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5 - Final Project/ssm2603_i2s.vhd}
  {C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/imports/Lab5Files/Lab5.vhd}
}
read_ip -quiet {{C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/sources_1/ip/pxl_clk_gen/pxl_clk_gen_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/constrs_1/imports/Lab5Files/Lab5.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/siddh/Desktop/Lab5 - Final Project/lab5.srcs/constrs_1/imports/Lab5Files/Lab5.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Lab5 -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Lab5.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Lab5_utilization_synth.rpt -pb Lab5_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
